from . import syntax

import datetime
import sys

class Generator:
    def __init__(self, out):
        self.w = syntax.Writer(out)

    def copy(self, source, target):
        self.w.build(outputs=str(target), rule="cp", inputs=str(source))

    def header(self):
        self.w.comment("Generated by \"{}\"".format(" ".join(sys.argv)))
        self.w.comment("at {}".format(datetime.datetime.utcnow().isoformat()))
        self.w.newline()
