#!/usr/bin/python3

import argparse
import datetime
import ninja_syntax
import os
import sys

polyMesh = [os.path.join("constant", "polyMesh", f) for f in ["points", "faces", "owner", "neighbour", "boundary"]]

def write(blockMeshCase, sourceMountainDict, case, sourceControlDict=os.path.join("src", "controlDict")):
    targetMountainDict = os.path.join(case, "system", "mountainDict")
    targetControlDict = os.path.join(case, "system", "controlDict")

    n = ninja_syntax.Writer(sys.stdout)
    n.comment("Generated by {}".format(sys.argv[0]))
    n.comment("at {}".format(datetime.datetime.utcnow().isoformat()))
    n.newline()
    n.build \
    ( \
            outputs=[os.path.join(case, f) for f in polyMesh], \
            rule="terrainFollowingMesh", \
            inputs=targetMountainDict, \
            implicit=[os.path.join(blockMeshCase, f) for f in polyMesh] + [targetControlDict], \
            variables={"blockMeshCase": blockMeshCase, "terrainFollowingMeshCase": case} \
    )
    n.newline()
    n.build(outputs=targetMountainDict, rule="cp", inputs=sourceMountainDict)
    n.build(outputs=targetControlDict, rule="cp", inputs=sourceControlDict)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate a terrainFollowingMesh .ninja file.')
    parser.add_argument('case', help="Target terrainFollowingMesh case directory")
    parser.add_argument('blockMeshCase', help="Case directory of the block mesh")
    parser.add_argument('mountainDict', help="Location of the mountainDict file")
    args = parser.parse_args()

    write(args.blockMeshCase, args.mountainDict, args.case)
